title = "ICP Foundation"
baseURL = "https://3duu6-syaaa-aaaad-qadtq-cai.ic.fleek.co"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "ICP Foundation"
    weight = 2
    contentDir = "content/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "https://storageapi.fleek.co/lyswifter-team-bucket/ice-foundation/favicon.ico"
  site_logo = "https://storageapi.fleek.co/lyswifter-team-bucket/ice-foundation/icp-small.png"
  description = "the very beginning place of Dfinity and the Internet Computer"
  facebook = "https://www.facebook.com/dfinity.org"
  twitter = "https://twitter.com/dfinity"
  instagram = ""
  youtube = "https://www.youtube.com/dfinity"
  github = "https://github.com/dfinity"
  gitlab = ""
  linkedin = "https://www.linkedin.com/company/dfinity"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "https://storageapi.fleek.co/lyswifter-team-bucket/ice-foundation/village-travel-original.jpg"
  recent_posts_number = 10
